# -*- coding: utf-8 -*-
"""hpc1-labwork1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17iTT8pgH_xJ7cSm7J7k1bcgdmyF2Uiv-
"""

!find / -iname 'libdevice'
!find / -iname 'libnvvm.so'

import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/local/cuda-10.0/nvvm/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so"

!nvidia-smi

from numba import cuda
cuda.detect()

cuda.list_devices()

cuda.list_devices()

from numba.cuda.cudadrv import enums
from numba import cuda

device = cuda.get_current_device()
attribs= [name.replace("CU_DEVICE_ATTRIBUTE_", "") for name in dir(enums) if name.startswith("CU_DEVICE_ATTRIBUTE_")]
for attr in attribs:
    print(attr, '=', getattr(device, attr))

print('Clock rate:')
print(getattr(device,'CLOCK_RATE'))

print('Multiprocesor count: ')
print(getattr(device, 'MULTIPROCESSOR_COUNT'))

print('Memory size: ')
print(getattr(device, 'TOTAL_CONSTANT_MEMORY'))